### ISSUE TITLE
Admin access

### ISSUE THREAD

**Issue by m49n** [mercurykd/vpnbot#1]
Возможность добавлять в  конфиг id телеграм юзеров которые смогу общаться с ботом для получения данных о подключениях и создании новых конфигов.

Реализовал это еще в первой версии, достаточно удобно, потом что без этой функции любой кто найдет телеграм бота сможет создать себе подключение.

**Comment by mercurykd** [comment]
[298fd4e1bb15bb0ffa2ddb0b8ce640c9c15c3bcc](https://github.com/mercurykd/vpnbot/commit/298fd4e1bb15bb0ffa2ddb0b8ce640c9c15c3bcc)
