### ISSUE TITLE
port?

### ISSUE THREAD

**Issue by Vanek9999** [mercurykd/vpnbot#19]
Error response from daemon: driver failed programming external connectivity on endpoint nginx-1.42.1-2-g66f0370 (112434c8abdf15cf6afd4c8db54e11d41e125148d11318f7bdce2a92a6182c29): failed to bind port 0.0.0.0:80/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
make: *** [makefile:6: u] Error 1

**Comment by Vanek9999** [comment]
Прошу помочь?

**Comment by mercurykd** [comment]
> 0.0.0.0:80: bind: address already in use

порты 80, 443, 853, 8443, 51820, 51821, 8388 должны быть не заняты в системе

**Comment by Vanek9999** [comment]
Если занят, то что делать

**Comment by mercurykd** [comment]
> Если занят, то что делать

смотреть что занимает порт и освобождать. рекомендуется ставить на чистую впс

**Comment by Vanek9999** [comment]
Спасибо!

**Comment by Vanek9999** [comment]
оперативно
