### ISSUE TITLE
не работает телеграмм бот

### ISSUE THREAD

**Issue by ring-rong** [mercurykd/vpnbot#3]
создал бота в телеге, взял его токен, подставил в эту команду wget -O- https://raw.githubusercontent.com/mercurykd/vpnbot/master/scripts/init.sh | sh -s YOUR_TELEGRAM_BOT_KEY
запустил ее, команда завершилась, но в телеге бот не стартанул, в чем проблема?

**Comment by mercurykd** [comment]
команда завершилась чем?
`make ps` в папке бота и скрин сюда

**Comment by ring-rong** [comment]
![Screenshot from 2023-05-02 17-21-13](https://user-images.githubusercontent.com/132333846/235604916-34235bc5-02fc-4a37-a25c-7d6479b064a0.png)
![Screenshot from 2023-05-02 17-24-08](https://user-images.githubusercontent.com/132333846/235604947-9a9280a8-981c-439b-bea5-e9a91f48146a.png)

**Comment by mercurykd** [comment]
судя по всему запущено на домашней ubuntu а не впс
доступность для телеграма вашего айпи проверяли? это реализация с вебхуками, телеграм стучится вот сюда https://$ip/tlgrm?k={$this->key}. если вы сидите за nat надо пробрасывать порты 80/443/8388/51820, ну и белый айпи нужен

**Comment by xykaxayc** [comment]
![2023-05-19_18-45-35](https://github.com/mercurykd/vpnbot/assets/84601072/23e83395-c8b1-49d3-b5e2-66ab8983da62)
вот так на впс, что можно сделать?

**Comment by mercurykd** [comment]
> ![2023-05-19_18-45-35](https://user-images.githubusercontent.com/84601072/239523878-23e83395-c8b1-49d3-b5e2-66ab8983da62.png) вот так на впс, что можно сделать?

а что не так?

**Comment by xykaxayc** [comment]
> > ![2023-05-19_18-45-35](https://user-images.githubusercontent.com/84601072/239523878-23e83395-c8b1-49d3-b5e2-66ab8983da62.png) вот так на впс, что можно сделать?
> 
> а что не так?

не запускается телеграм бот

**Comment by mercurykd** [comment]
> не запускается телеграм бот

очень мало информации, тем более что на скрине все ок
в папке logs посмотрите php_errors, мб там что есть.
https://t.me/vpnbot_group тут могут подсказать

**Comment by 5k1n** [comment]
Добрый день! а есть команда как удалить всё это с сервера? не затронув действующие настройки ВГ, которые были до бота.
