### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by MrKira34** [mercurykd/vpnbot#7]
Подскажите, пожалуйста.
Как накатить все ваши обновления, не потеряв свои старые коннекты, которые уже создал.

Устанавливал ваш скрипт так:
wget -O- https://raw.githubusercontent.com/mercurykd/vpnbot/master/scripts/init.sh | sh -s YOUR_TELEGRAM_BOT_KEY
Заменив YOUR_TELEGRAM_BOT_KEY на свой токен.

Как теперь это дело обновить?

**Comment by mercurykd** [comment]
зависит от сложности обнов. в обычном случае: зайти в папку бота
```
git pull
make r
```
